### ISSUE TITLE
xcode 12.4 build error： Undefined symbol: _OBJC_CLASS_$_ATTrackingManager [iOS 14.4]

### ISSUE THREAD

**Issue by Erica-Jiangyf** [mrousavy/react-native-tracking-transparency#10]
Hey am sorry to bother again but your advice is very valuable.

I'm running iOS 14.4 on an iPhone 12 Pro Max[14.4],but it always has an error ：
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ATTrackingManager", referenced from:
      objc-class-ref in libTrackingTransparency.a(TrackingTransparency.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
“Undefined symbol: _OBJC_CLASS_$_ATTrackingManager”

I try to change the build setting and build path to fix it，but it didn't work。

How can i do to fix it？

Thank you

**Comment by mrousavy** [comment]
Try cleaning and rebuilding

**Comment by Erica-Jiangyf** [comment]
> Try cleaning and rebuilding

I clean the project and clean the DerivedData，but it still didn't work.
