### ISSUE TITLE
'TrackingTransparency.mm' cannot be found

### ISSUE THREAD

**Issue by Erica-Jiangyf** [mrousavy/react-native-tracking-transparency#11]
When i build the app and i'm getting this issue:

`Build input file cannot be found: '/Users/ejiang/Project/TKPro/TKPro-mobile/packages/tkp-mobile/node_modules/react-native-tracking-transparency/ios/TrackingTransparency.mm' (in target 'TrackingTransparency' from project 'TrackingTransparency')`

If i fix the '.mm' to '.m' in the file(/ios/TrackingTransparency.xcodeproj/project.pbxproj),it will build success.But in production，i can't fix this file.

Is there  any other idea  to fix it?

**Comment by mrousavy** [comment]
Fixed in 0.1.1, thanks for the report!
