### ISSUE TITLE
Not working on real device

### ISSUE THREAD

**Issue by ugrdursun** [mrousavy/react-native-tracking-transparency#12]
It perfectly works on simulator with debug variant but not on real device with production variant. 

any suggestion ?

**Comment by ugrdursun** [comment]
It turns out iOS 14.5+ required. I think something wrong with previous versions of OS, so its OS issue. Updated my real test device to 14.6 and its working fine.

**Comment by gpontes98** [comment]
> 
Hi,
I'm having the same problem, when I install on the real device, the att doesn't appear what can i do?
