### ISSUE TITLE
What happens when the user clicks Ask App Not to Track

### ISSUE THREAD

**Issue by Ruzen1** [mrousavy/react-native-tracking-transparency#3]
Hey @mrousavy 
         Thank you for the library.
Can you tell me what happens if the user clicks on 'Ask App Not to Track'. I tried it but its normally using the locations which was not supposed to.
Thank you

**Comment by mrousavy** [comment]
That's still an optional feature which will be required by apple soon. For now you should follow the users request, as your app might be blocked in the future if you dont

**Comment by Ruzen1** [comment]
@mrousavy Thank you so much for the response. So basically, we just show the dialog box for formality right ?

**Comment by mrousavy** [comment]
I recommend you read the [App Tracking Transparency](https://developer.apple.com/documentation/apptrackingtransparency?language=objc) guide

**Comment by Ruzen1** [comment]
@mrousavy Thank you again. Yes, I have read it. But I wasnt clear if it was required for my app. Because, the data is actually not being used by other apps. However, we are using the data for different purpose rather than advertising. So, if the user denies the app tracking transparency, is there anything I should do inside the codes or we should just get the status of app tracking transparency for each user and then stop the task we do if its denied.
your advice is highly appreciated. Thank you

**Comment by mrousavy** [comment]
I think you're better off asking that question in the Apple Developer FAQs - I only use this library to disable Facebook Ad tracking if the user doesn't want to be tracked. So sorry, I don't know the answer to your question.

**Comment by Ruzen1** [comment]
I see. Thank you anyway. :) your library is really helpful
