### ISSUE TITLE
Does this work for React Native Expo?

### ISSUE THREAD

**Issue by NyashaNziramasanga** [mrousavy/react-native-tracking-transparency#6]
Im using react native expo and im getting this issue:

```
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'TrackingTransparency.requestTrackingPermission')]
```

Any idea on how to fix it?

**Comment by mrousavy** [comment]
yes, eject from expo managed. This is a native module

**Comment by niloufarzahiri92** [comment]
Does this work on the simulator? because in the simulator the requestTrackingPermission() dose not work
