### ISSUE TITLE
firebase crashlytics report: FBSDKSKAdNetworkReporter (After version of ATT)

### ISSUE THREAD

**Issue by cnhsttyle** [mrousavy/react-native-tracking-transparency#7]
After version of react-native-tracking-transparency (ATT) applied
Firebase Crashlytics reports crashes, such as attached images.
(FBSDKSKAdNetworkReporter.m line 92 / Fatal Exception: NSInvalidArgumentException)

<img width="802" alt="firebase_crash" src="https://user-images.githubusercontent.com/15974698/117619062-c1909700-b1a9-11eb-9df5-f4ff6ccceeae.png">

I am currently using react-native-fbsdk-next. (FB SDK >= 9)
What should I do to fix the problem?
Thank you.

**Comment by mrousavy** [comment]
Why do you think this has anything to do with ATT?

**Comment by cnhsttyle** [comment]
> Why do you think this has anything to do with ATT?

Because it is a bug reported in the version after ATT application.
I thought it might have something to do with ATT...

Is it not related to ATT?

**Comment by mrousavy** [comment]
In the crash' stacktrace you sent me there is a clear indication that this is coming from FBSDK, but this does not have anything to do with ATT. Maybe you're better off reporting this bug to the react-native-fbsdk-next library you're using.

**Comment by cnhsttyle** [comment]
Okay!
Thank you
