### ISSUE TITLE
Why duplicate react-native-permission?

### ISSUE THREAD

**Issue by mikehardy** [mrousavy/react-native-tracking-transparency#8]
https://github.com/zoontek/react-native-permissions

Includes app tracking transparency and is rigorously maintained and response :thinking:  ?

**Comment by mrousavy** [comment]
only god knows

**Comment by mikehardy** [comment]
Think of all the other hacking you could do instead of maintaining this ;-). But I thought you may have a valid reason - frequently there is one and I was curious. Either way, cheers :-)

**Comment by mrousavy** [comment]
no, I can't really remember why I created this library. Either I was just trying to learn more about native modules, or ATT was not available in permissions at that time? No idea haha

**Comment by mikehardy** [comment]
This is splitting the community, everyone sees this repo first I guess while searching. You should consider consolidating with react-native-permissions IMHO unless there's a reason to maintain a duplicate codebase for same permission here
